version: '3.9'
services:
    cloudflared:
        networks:
        - proxy
        command: 'tunnel --no-autoupdate run --token (token de cloudflare)'
        image: 'cloudflare/cloudflared:latest'
        restart: unless-stopped
        container_name: cloudflare
networks:
  proxy:
    external: true

