version: '3.8'

services:
  beszel:
    image: henrygd/beszel
    container_name: beszel  # Aquí le damos el nombre que deseas
    restart: unless-stopped
    ports:
      - "8090"
    volumes:
      - ./beszel_data:/beszel_data
    networks:
      - nointernal_manager
    hostname: beszel

networks:
  nointernal_manager:
    external: true  # Usamos una red externa llamada nointernal_manager
