version: "3.8"

services:
  excalidraw:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    ports:
      - "3030:80"
    restart: on-failure
    networks:
      nointernal_home:
        aliases:
          - draw
    hostname: draw

networks:
  nointernal_home:
    external: true
